# Generated by Django 2.1.8 on 2019-05-14 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor3',
            field=models.TextField(blank=True),
        ),
    ]
