# Generated by Django 2.1.8 on 2019-05-14 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20190514_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rec_users',
            field=models.ManyToManyField(blank=True, related_name='rec_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
