# Generated by Django 2.1.8 on 2019-05-15 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20190515_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_rec_users',
            field=models.ManyToManyField(blank=True, related_name='not_rec_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
